DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS chats CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS members CASCADE;
DROP TABLE IF EXISTS attachments CASCADE;

DROP INDEX IF EXISTS user_nick_idx;